	
	-- 1. Tắt kiểm tra khóa ngoại để tránh lỗi 3780
	SET FOREIGN_KEY_CHECKS = 0;

	-- 2. Đồng bộ Database mặc định
	ALTER DATABASE QuanLyTaiSan CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE bangiaoccdcvattu CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE bangiaophuluc CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE bangiaotaisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE ccdcvattu CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE chitietbangiaoccdcvattu CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE chitietbangiaophuluc CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE chitietbangiaotaisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE chitietdieudongccdcvattu CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE chitietdieudongphucluctaisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE chitietdieudongtaisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE chitietdonvisohuu CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE chitietketquasuachua CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE chitietsuachua CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE chitiettaisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE chucvu CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE config CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE congty CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE dieudongccdcvattu CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE dieudongphuluctaisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE dieudongtaisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE donvitinh CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE duan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE flyway_schema_history CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE hientrangkythuat CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE kehoachchitietsuachua CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE kehoachcongviecsuachua CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE kehoachsuachua CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE ketquasuachua CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE khauhao CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE kho CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE kytailieu CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE lichsudieuchuyenccdcvattu CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE lichsudieuchuyentaisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE loaiccdccon CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE loaiscbd CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE loaitaisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE loaitaisancon CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE lydotang CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE mohinhtaisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE nguoiky CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE nguonkinhphi CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE nguonvon CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE nhanvien CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE nhomccdc CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE nhomdonvi CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE nhomtaisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE permission CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE phongban CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE phuluctaisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE role CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE rolepermission CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE sequence CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE setnguonkinhphi CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE suachua CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE taikhoan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE taisan CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE taisancon CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE thuoctinhnhanvien CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE userpermission CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE userrole CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
	ALTER TABLE version CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;