-- Thêm 10 trường cấu hình tiêu đề vào bảng mau_bien_ban_sua_chua
ALTER TABLE mau_bien_ban_sua_chua
    ADD COLUMN Trai1 VARCHAR(255) NULL,
    ADD COLUMN Trai2 VARCHAR(255) NULL,
    ADD COLUMN Trai3 VARCHAR(255) NULL,
    ADD COLUMN Phai1 VARCHAR(255) NULL,
    ADD COLUMN Phai2 VARCHAR(255) NULL,
    ADD COLUMN Phai3 VARCHAR(255) NULL,
    ADD COLUMN ThoiGian VARCHAR(255) NULL,
    ADD COLUMN Giua1 VARCHAR(255) NULL,
    ADD COLUMN Giua2 VARCHAR(255) NULL,
    ADD COLUMN Giua3 VARCHAR(255) NULL;
