ALTER TABLE PhieuGiaoViec ADD COLUMN GhiChuBienBan TEXT;
ALTER TABLE PhieuGiaoViec ADD COLUMN CongTy VARCHAR(255);
ALTER TABLE PhieuGiaoViec ADD COLUMN TenMauBienBan VARCHAR(255);

ALTER TABLE PhieuLinhVatTu ADD COLUMN GhiChuBienBan TEXT;
ALTER TABLE PhieuLinhVatTu ADD COLUMN CongTy VARCHAR(255);
ALTER TABLE PhieuLinhVatTu ADD COLUMN TenMauBienBan VARCHAR(255);

ALTER TABLE nghiemthu ADD COLUMN GhiChuBienBan TEXT;
ALTER TABLE nghiemthu ADD COLUMN CongTy VARCHAR(255);
ALTER TABLE nghiemthu ADD COLUMN TenMauBienBan VARCHAR(255);

ALTER TABLE danhgia_vattu ADD COLUMN GhiChuBienBan TEXT;
ALTER TABLE danhgia_vattu ADD COLUMN CongTy VARCHAR(255);
ALTER TABLE danhgia_vattu ADD COLUMN TenMauBienBan VARCHAR(255);
