ALTER TABLE DieuDongTaiSan ADD COLUMN taiLieuCuoi TEXT;
ALTER TABLE DieuDongCCDCVatTu ADD COLUMN taiLieuCuoi TEXT;
ALTER TABLE BanGiaoTaiSan ADD COLUMN taiLieuBangKe TEXT;
ALTER TABLE BanGiaoCCDCVatTu ADD COLUMN taiLieuBangKe TEXT;
