ALTER TABLE CapSuaChua ADD COLUMN IdLoaiTaiSan VARCHAR(50);
ALTER TABLE CapSuaChua ADD COLUMN MocGioDau INT;
ALTER TABLE CapSuaChua ADD COLUMN MocGioCuoi INT;

ALTER TABLE DinhMucSuaChua DROP COLUMN IdLoaiTaiSan;
