CREATE TABLE ChuKySuaChua (
    Id VARCHAR(255) PRIMARY KEY,
    IdTaiSan VARCHAR(255) NOT NULL,
    IdLoaiSuaChua VARCHAR(255) NOT NULL,
    ChuKy INT NOT NULL,
    DonViChuKy VARCHAR(50) NOT NULL
);
