services:
  # qlts_reverse_proxy_service:
  #   image: ${REGISTRY}/qlts_reverse_proxy_img:${VERSION}
  #   ports:
  #     # HOST_PORT:CONTAINER_PORT
  #     - "7777:8888"
  #   stdin_open: true
  #   environment:
  #     - TZ=Asia/Ho_Chi_Minh
  #   networks:
  #     - frontnet
  #   depends_on:
  #     - qlts_frontend_service

  qlts_frontend_service:
    image:
      ${REGISTRY}/qlts_frontend_img:${VERSION}
      # target: development
    ports:
      # HOST_PORT:CONTAINER_PORT
      - "9999:80"
    stdin_open: true
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      # For development only, to synced src code to container
      - /usr/src/app/node_modules
      # restart: always
    networks:
      - frontnet

networks:
  frontnet:
