export const ROUTES = {
  LOGIN: "/login",
  MAIN: "/",
  STAFF: "/nhan_vien",
  DEPARTMENT: "/phong_ban",
  POSITION: "/chuc_vu",
  PROJECT: "/du_an",
  CAPITALSOURCE: "/nguon_von",
  TYPEASSET: "/loai_tai_san",
  TOOLGROUP: "/nhom_ccdc",
  TOOLTYPE: "/loai_ccdc",
  UNIT: "/don_vi_tinh",
  REASONINCREASE: "/ly_do_tang",
  CURRENTSTATUS: "/hien_trang",
  ASSETMANAGER: "/quan_ly_tai_san",
  ASSETTRANSFER: "/dieu_dong_tai_san",
  ASSETDEPRECIATION: "/khau_hao_tai_san",
  TOOLMANAGER: "/quan_ly_ccdc",
  TOOLTRANSFER: "/dieu_dong_ccdc",
  REPORT: "/bao_cao",
} as const;
